---
title: "R for science communication and culture"
subtitle: 
author: "[Julie Lowndes](https://jules32.github.io/) @juliesquid, @RLadiesSB"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      output:
    css: ["default", "rladies", "rladies-fonts"] #https://alison.rbind.io/post/r-ladies-slides/
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE, warning=FALSE, message=FALSE, verbose = FALSE)

library(xaringan)
```

<!---
KEEP IN MIND

Environmental scientist doing research. "How can we bring this to science" is way too big
When I say science = = "bring #rstats to science" what does that mean
"when I say bring to science the level I'm talking about is here" 


TOO MANY WORDS> the most important things get lost if each is a full paragraph

each slide is 2-3 sentences. percision of speech. every word should be throughful and precise. to create emphasis of tihngs


instead of saying "i've been thinking a lot about" "the question I ask: how can we bring this ethos to env sci". That's been guiding my efforts

add one sentence: environmental problems are critical. what a bummer what they don't 

storyline is good in the intro. Stop changing it. This is good. Get the words nailed down so that they're great and precise. 

Then, we can talk about whether we don't talk about env science enough. WEDS

in next few days say intro bare bones. 

R has changed my life, and so much that now I'm actively working to have it to change the lives of more scientists like me.

DON"T SAY IT ALL THEY CAN ASK QUESTIONS> DON"T ADLIB

Next time: stand up and present!
SUMMARIZE AS A HEADER

people love feeling they're smart and they love feeling they're making progress (so get off the title slides)
--->

# R and data science have incredible potential accelerate scientific research.

???

Thank you so much, it is so amazing to be here with all of you and I want to thank the organizers for this invitation. 

R and data science have incredible potential accelerate scientific research. They can help uncover solutions to our most pressing problems, which in the environmental space include food security and sustainable resource use on land and in the oceans.  

--
# But many environmental scientists are being excluded from this potential.  

???

But many environmental scientists like me are being excluded from this potential. 

--
# We lack opportunities to learn and we lack a supportive scientific culture.

???

We are excluded because we lack opportunities to learn data science and we lack a supportive scientific culture to incorporate it into our research. 

Right now, there are many disciplines in the environmental space that do not value data science and open practices. 

And I say this because on the whole we do not teach data science and open practices in environmental disciplines, and we do not reward them. 

It is not even a part of our current culture to talk about data practices, and so as individuals we do not even have the mindset or even the vocabulary to do so. *[There are not a lot of paths to participate; you have to seek them out on your own and make the time.]*

This means we do not see examples of its benefits in our own context, and we do not see welcoming entry points to engage. 

---
# But #rstats can help

???

But I know that we can change this culture in environmental science, and we can do it following the example of our #rstats community here. 

I know this because I have lived through this mindset change myself, and I have spent the last 6 years igniting cultural change in environmental science by working with colleagues around the world. 

transition: So let's talk about what it's like to be an environmental scientist.

---
r4ds minus hadley — environmental side. 

(how interdisc and public good)

???

Environmental scientists have a lot in common with the open source community because we are working for the public good, and passionate about our work. 

This is actually not a distinct discipline, but a collection of scientists working at the interface of environment, ecology, and people. 

We are biologists, ecologists, physiologists, and many other -ists.

We are are also deeply interdisciplinary, and are experts in the many different domains we work in. For example, scientists studying freshwater availability need to work across domains like hydrology and ecology, agriculture and politics. 

For my PhD work I needed to learn about oceanography and fisheries in addition to the behavior and physiology of the squid I studied, and the local ecosystem dynamics in the Pacific Ocean off California. 

As a marine ecologist, my world was filled with learning about oceanography, fisheries, physiology, and local ecology to also design my questions around squid behavior.

---
r4ds minus hadley — environmental + communications

???

And our resulting findings are really impactful for society. Our findings help understand climate change, food systems, and drought. And this means that communication and collaboration are really important. We are often working with government bodies at local and international scales *[to...]*

To do all this, we collect and work with a lot of data. 

transition: To be able to analyze our data, most of us do end up coding to some degree. 

---
r4ds minus hadley — environmental + communications with big sad face in the middle

???

But learning to code is an individual, isolating struggle. 

Throughout our education we are rarely formally taught to code or work responsibly with data. 

Somehow we assume that we are the only one who doesn't get it so we don't talk about it. [There's this sense that figuring out how to responsibly analyze data is part of the scientific discovery process, meaning you do it alone and the first to ever want to convert date formats from Excel.]

And this makes coding a really intimidating thing to learn on our own. We resist it as long as we can before scrambling to learn just enough to get the job done at the last moment, usually in a total panic. 

And this means we're not really proud of our code, which means we are less inclined to talk about it, and resistant to sharing it. And this perpetuates the culture of not talking about data and coding, and therefore not valuing it. 

---
# To be very clear

???

I want to be really clear that I am not trying to disparage environmental scientists. 

--

- Environmental scientists are doing good work that is important & impactful

???

We are doing really important, impactful work. And this work is on challenging, complex systems, many of which are front lines seeing the effects of climate change, which is emotionally draining.

--

- Some do value data science & open practices 

???

Also, I know there are many examples of environmental scientists who do value data science and open practices — there are many in this room. 

--
- But broadly, we are not learning skills to work responsibly with data

???

But, we need to be honest that we are not being formally taught the fundamental skills we need to work responsibly with data. Our culture as a whole does not value data science and open practices when we do not have any time to waste. 

transition: And I am convinced that R can help here. 

---
# r4ds complete 

???

R streamlines how we work with data, and also streamlines how we work with each other. 

And the R community has really focused on creating a positive space for people like me to be welcomed as human beings and encouraged as coders.

And it is so powerful for innovation and collaboration, which is the heart of science. 

So with I want to do is not only welcome more environmental scientists to the R community, I want to simultaneously extend our values and our ethos to environmental science.

transition: So over the past year with my Mozilla Fellowship, I've developed a program called Openscapes.

---
# (outline slide)
Openscapes hex - right 

???

With Openscapes I'm focusing on building this culture at the core community unit of science, the research group or laboratory. 

Openscapes is a mentorship program for research groups, helping them engage with open data science and become visible examples and vocal champions for open data science within their broader communities. 

We've just completed the pilot cohort of this mentoring program with 7 research groups, and I'm excited to tell you all about it bc I am so proud of what they accomplished.

--
add OHI hex - left

???

But to tell the Openscapes story I need to first tell the Ocean Health Index story. It's because I designed the Openscapes program based on the struggles and wins our own team experienced.


So this is what I will focus on for the rest of the talk.

Probably the biggest takehome message is about how we can all be leaders in welcoming others into R and extending the R community.


---
OHI hex, bigger centered

???

The first example is the Ocean Health Index.

There is a lot to say about OHI but I want to focus on how R enabled a culture change. It was not only easier to do analyses better, we can communicate better with each other and more broadly with collaborators, partners, stakeholders — something that has been limiting in science when you're forwarding PDFs to each other. 

And there is no way that we could have so much reach and impact without #rstats and the ODS community.

---
OHI measure illustration
Q for Allison:: I would love to show the team early instead of at the end, not sure it works early though.

???

The ocean health index is a project to measure what we value about our oceans using the best available data and science. 

It is a really ambitious project. 

It set out to be the best approach for data-driven marine policy around the world, and indeed now it is used by the United Nations and also by twenty government and university groups. 

transition: We didn't set out to be the best approach for what open data science could look like in environmental science —

---
nature paper (authors only no abstract)

> We are among the many environmental scientists who were never formally trained to work deliberately with data. Thus, we were unaware of how significantly open data science tools could directly benefit our research11,73, and upon learning about them we were hesitant, or even resistant, to engage. However, we were able to develop confidence in large part because of the open, inclusive and encouraging online developer community that builds tools and creates tutorials that meet scientists where they are

???

But when we shared our path to better science in less time in 2017, it really resonated with a lot of people. 

It is a retrospective of how we incrementally introduced R and GitHub into our workflow over a period of four years.

It lays out how tools like R and GitHub helped change the culture of our science, by focusing on reproducibility, collaboration, adn communication. 

I won't go through all of this here but I want to give some highlights, and particularly focus on how R and GitHub really redefined what communication means for us in science. 

Being able to efficiently share and communicate our work while it is ongoing rather than only post-publication has been really critical for us bridging science and policy. 

---
Figure 1

???

This is an illustration from the paper conveying how much less time it took... 

I joined the team in 2013 when we were supposed to update the data, 

transition: So back in 2013. this is where we were starting from 

<!---
image of a house blueprint.
Q for Allison: maybe skip this blueprint completely?

???

The Ocean Health Index is essentially a blueprint for measuring ocean health. 

A blueprint for a house would include walls, floors, and a roof, but houses around the world look different because of the materials available and local conditions. For example, houses look different in places with different amounts of snow, rain, or sun. 

The Ocean Health Index blueprint includes things that provides benefits to people, and that people can manage. So it includes the seafood we eat, jobs, tourism, the habitats that mitigate storm damage, and includes pressures affecting these benefits like climate change, as well as management policies that can counteract those pressures.

transition: 


screenshot Halpern et al. 2012

???

It took almost 4 years to develop this blueprint. 

At the same time we used it to calculate ocean health scores for all 220 coastal countries globally. 

This included almost 100 publicly data sets from the United Nations, World Bank, as well as synthesis studies and satellite data. 

The plan from the beginning was to repeat this global study each year, because the value of the OHI is not in doing it once, but in tracking change through time and acting upon the most pressing needs. 

So we had a plan for reproducibility, with attention to documentation. 

transition: 

--->

---
# We thought we were being reproducible 

data_analysis_v2.xls
re:fwd:final data updated

???

This is where we started from. 

Data processing was done with whatever tools different people knew. Most was in excel and a bit in R, with decisions documented in accompanying Word documents and emails. 

A single teammember would write models in whatever language best suited the data, and develop the models around whatever structure that data set was in. 

So the next year when we went to repeat the analysis, there was a lot of forensics and detective work to uncover what we had done the first time, and why. 

For that second year there was also turnover in the team: that was the year I joined and others moved on.  

Needless to say, we needed a better system. So here is what we do now. And again, this was over a four-year period, and we continue to iterate and improve. 

---
# Actually being reproducible 

Maybe just include part of [Table 1](https://www.nature.com/articles/s41559-017-0160/tables/1)? 

(maybe bullet this, and animate?)

GitHub norms

- create a GitHub organization, everyone makes an account
  - including our team lead (not hands-on data)
- private "issues" repo for discussing methods
  - institutional memory, onboarding & offboarding
- use RStudio & GitHub (version control)

R norms

- all data prep, models, viz in R
- coding norms: `tidyverse` & friends
- separate core "blueprint" models into R package `ohicore`
- separate local "tailorable" models into separate repos 
- data prep narratives in R Markdown

???

---

GitHub

- distribution
- troubleshooting/IT
- publishing

R norms

- single webpages (e.g. supplemental materials)
- ohi-science.org website (Jekyll) 
- assessment websites (simple RMarkdown)
- books (bookdown)
- shiny apps

---
ohi-science.org

???

we also created a website with R and friends for our Ocean Health Index community so that we could get beyond forwarding PDFs and writing individual emails. 

The home page is with Jekyll

transition: we also generate simple RMarkdown websites for each as well: ohi-global 

---
ohi-global website

???

These simple RMarkdown websites have been SO valuable for us. We can auto-generate them for any country, we probably have 30 of them that we've made.

---
OHI Cornwall

???

Here's another example

---
github for communication

- private repo for all issues
  - methods discussion in one place
  - good for onboarding new team members
  - our boss gets these as emails and can review & contribute from email
- everyone on our team has admin priveleges e
  - very few branches & pull requests
- push & pull for IT/troubleshooting

???

We use GitHub in a few perhaps unconventional ways. 

---
toolbox-training

???
to teach people how to use our software, we've been working on a book

---
data-science-training

???

and we also realized we needed to teach groups how to work with #rstats and Github like we do.

---
ohi-northeast dashboard

???
We are also using shiny in a few ways, but I think this is one of the coolest. 

We are leading OHI Northeast, and it is actually included in part of President Obama's ocean plan. 

The code is based from XXX's, who we saw present at RStudio::conf 2018. 

---
Box 1 & 2

???

How we did this was NSSD, etc. 

---
map? 

???

At this point, like I said, OHI is used by 20 groups around the world, and will be included in the UN's ocean indicators for the Sustainable Development Goals. 

This would not have been possible without #rstats. 

We are a streamlined team, able to onboard and offboard teammembers, we work well together, and we are able to iterate from past work and enable others. 

By 2018, I had been working for 5 years, not only to help with the global assessments, but to co-develop and lead the program for the independent groups. 

We had published the Nature paper, and could see it being well-received in some circles. 

But I wanted to actually help other teams do this themselves. 

transition: that's when I got the Mozilla Fellowship and started Openscapes. 

---
# OHI team qualities (circa 2014)

- someone really jazzed about #rstats (Ben Best)
- a boss/project lead who valued it & gave us space to learn (Ben Halpern)
- welcoming people from the #rstats community (Karthik Ram, Hadley Wickham, Joe Cheng)
- trust & willingness to learn together
- complementary/overlapping skillsets (not everyone codes)

???

Finally, I have to talk about our team. 

We were able to do all of this not only because of the tools, but because of the people involved. 

---
(maybe just the center/hadley culture part of R4DS illustration?)

???

And I need to talk about our communities

rOpenSci, RStudio, Carpentries, Twitter. 

- Carpentries instructor 
- Eco-Data-Science
- RLadiesSB

---
# software <-> teamwork 
(spiral? porridge?)

???

All of this has had me thinking about how software enables teamwork and teamwork enables software. I'm going to try talking about this here; I have trouble articulating it but think it is really critical for moving forward. 

So thinking about it from the software side, there is software that is designed to streamline teamwork. So for example, Google Docs lets you co-edit and therefore co-think together in real time. GitHub helps you collaborate with others. And there are also things like the tidyverse that help create shared social norms that make it easier to work as a team. 

On the other side, if you are on a team or community you might have more courage to engage in new software; RLadies chapters, meetup groups, #tidytuesday

So for a lot of us in this room, this turns into a feedback loop and get almost difficult to differentiate and tease apart. so it might be less of a loop but more like a porridge...

And OHI is an example where one person with knowledge of the software enabled the team to engage, which meant more of us were using the software, which then strengthened the team norms and culture. 

And eco-data-science starts at the other side maybe, where it was a group of friends asking one person with knowledge of R how to learn, so it went from the team to the software and then 

But the reason I'm thinking about this is because of entry points. What if you are outside of this loop. You might use software, but not really with any collaboration or teamwork in mind. Maybe you don't even feel like you're part of a team. 

How do you engage and welcome people in those cases? 

transition: thinking about this was a big part of how I designed Openscapes. Really wanted to focus on how software can streamline teamwork and teams can learn how to use software.

<!---
# Nature paper reprise

???
But although we wanted to encourage others with our story, we've heard that people think it's just for established projects. This paper wasn't including people who didn't feel like they were part of a team. They 
--->
---
# Openscapes hex, center

Openscapes is a program to welcome environmental scientists to become champions for ODS. 

---
Openscapes

with early career faculty and lecturers. The reason I focus on early career lab groups is bc this is my generation of scientist, which means they have struggled with data as individuals and and it's s perfect opportunity to intervene and set a deliberate, r-inspired culture in their lab . 

particularly focused on ECRs. *[I do that because Without formal academic training, self-taught early career researchers are especially being left behind – and now in leadership positions as faculty, lecturers, and program managers, they are passing homegrown approaches to their labs. There is great opportunity to empower early career scientific leaders with our existing open science tools and communities so their labs can help uncover data-driven solutions faster.]*

<!---[place here for Star Wars?] Put this for Openscapes> THIS IS MINE. When I'm talking about this, this is how I describe it, give a nod to having used it before.--->

---
Selection requirements: 

early career scientific leads (col 1)
- faculty
- lecturers
- program managers
- etc

- rising star, influential scientists that can also become ambassadors for ODS
- not yet engaged in open data science
- trust that I will not waste their time

I decided to focus on early career scientific leaders for a few reasons
But I was also having a lot of one-on-one conversations with colleagues of mine, friends from grad school who were now running their own labs. 

Early career PIs might not yet know about the Force. They may have struggled through like Luke in their PhDs, worked their butts off to secure faculty jobs, and are now leading their own teams. How about focusing on them?


---

Explicit statement:::::::
there's this aspect of open tools and the aspect of community. and we want this to be both. transition in the analogy: but once luke learned to use the force, he didn't go out adn defeat the empire on his his own. he needed his community. 

We need to focus on the tools and also on the community. 



<!---
If we can do that in science — 

it's not tools, it's mindset. It's about seeing what's possible and being welcomed in. And I've been thinking about it not only from the data analysis and data science side, which is huge. 

transition: But in terms of welcoming environmental scientists, I've been thinking about it from the communication and culture side as well. 

---
R for science communication and culture

R has not only changed my analytical life, it's changed what's possible with science communication as well. and I think it can also change scientific culture; we can replicate/bring/remix what we have here in the #rstats community to environmental science, so that we put people first and can tackle these environmental issues. 

I'm going to tell you about an example of each: what's possible for env science and also for culture

---
nature paper screenshot

???

In a 2017 paper I led with my team, trying to be an example of what this can look like in science. 
we described how ODS helped us do better science in less time, how over the course of 4 years we incrementally introduced #rstats and github into our workflows and how it impacted the work we do and who uses it. And we identified 2 barriers: exposure and confidence. 

rstats is still not part of the culture of environmental science, so the 
There is a lack of exposure to what is possible, and a lack of confidence 

As a scientist, there are not a ton of pathways there, 

We found this on our own, had to seek it out. No one told us. Not a thing that is in the culture of science. 

transition: but what if it could be? so I want to give a two examples: what could this look like in environmental science? and how can we help welcome more scientists in?

---
# what does #rstats ethos look like in environmental science?

# how can we welcome others?  what if science prioritized community?

#



What's cool is that it opens up what communication can mean for science. It can make it more interactive, quicker. Science communication can mean publishing a peer-reviewed paper, it can mean talking with a journalist. It can mean tweeting, giving talks, etc. But now, with R, it can mean publishing books. It can mean 



???


how can we bring this welcoming and supportive culture to researchers in environmental science specifically who have such inmportant questions to answer but don't have the skillsets


I've been thinking a lot about having confidence with software leads to a more open and confident community. And how it's been this missing piece for scientists. What makes this happen is an investment in people and culture and community. 


transition:: what would it look like?


--->

---
2 hex stickers

???
So that is my work to this point, I'm fundraising to be able to lead Openscapes full-time, and am co-leading our OHI internship program. 

But I wanted to end with what we can all do to become leaders in our communities.


How do we motivate others?

Talk about and show your colleagues how R makes you 

- a data scientist

but also 

- an author
- a web designer
- a designer
- a community member
- a leader


???
Say this to your colleagues: R makes me xyz


---
open software -> open mindset & culture -> (looped) or 

rstats -> community & culture -> ) 

???
positive feedback loop

ggest challenges are env, enabling scientists are the best. 

conclusions: in a time where some of the big

---
#STAR WARS STUFF

<!---
But what happened then was that I quickly and sadly realized that I didn't have the tools or skillsets to work responsibly with my data. 

It was really demoralizing. And it was lonely and isolating. 

And the irony of feeling so alone is that most environmental scientists are also feeling lonely and isolated because of data. 

We are studying some of the biggest challenges our planets face, but we are largely on our own for data analysis. 

We are rarely formally taught how to code or work responsibly with data. Most of us do learn how to code on our own, but it is a painful, lonely process that we do just to get the job done. 

So that means we spend a lot of time reinventing the wheel and aren't proud of our code and aren't really eager for other people to see it. 

And we can feel like we are the only ones who feel this way so we don't really want to talk about it. 

transition: To drive home what this feels like, I like to talk about this with star wars analogies. 

---
Luke

???

<<Careful saying "scientists" generally w/o qualifier

This is Luke after he crashed his plane in the swamp on Degobah. 

He is there staring at a challenge that he cannot solve with the skillsets he has. 

It is super demoralizing, and he has no idea how to even begin this process. 

Imagine for a moment if he had tried to rig up some pullees and levers. 

It would not have been pretty. Or reproducible.

transition: but what happens next is that he meets Yoda 


Yoda

???

And Yoda has a skillset to solve this challenge solve Luke's problem in a way he never imagined: he uses the Force. 

And Luke can learn from Yoda, and he will develop skills to not only solve this problem, but it will open his mind to what is possible and the challenges he can take on. 

transition: But the Force alone didn't make Luke successful, it is the community that he is a part of. 

Hands

???

Luke's community is not only Jedis with the same skillsets he has. This is a movement made up of diverse people (and droids, wookies, and whatever yoda is) from different backgrounds, and all of them contribute in really important ways. 

So the Force is R or more broadly, it's open data science. And the community is us, the people in this room. 

transition: And we can help welcome more environmental scientists into this community because


# /#rstats
Hands w/ logos: RStudio, rOpenSci, RLadies, Carpentries, Mozilla


???

Our #rstats community is so amazing. 

It is welcoming, it is inclusive, it is supportive, it is empowering. 

There is such a mix of people from diverse backgrounds and experiences, from all over the world, online and in person, innovating and learning together. 

What's different about our community is that we put people first and are really here to share ideas and learn together. It's what science should feel like. . 

This has been so impactful for me as a scientist. Instead of feeling stranded in a swamp like I did when I was a PhD student, I feel more powerful than I ever imagined. 

You here in this room have helped me change the way I do science and the way I think about what is possible. You have empowered me and helped me build confidence that translates well beyond code. 

We are all here because we have been empowered by R as a tool and a community, but we can all probably think of others that are still feeling stranded and alone. We might work with them day-to-day. 

transition: So my question is 
--->

